name: ci

on:
  push:
    branches:
      - production

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Checkout Dockerfile repo
        uses: actions/checkout@v2
        with:
          repository: panos512/CMSKubernetes
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          context: ${{ github.workspace }}/docker/das2go/
          tags: panos512/das2go:latest