name: ci

on:
  push:
    branches:
      - production

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:

      - name: Pull CMSKubernetes repo
        uses: actions/checkout@v2
        with:
          repository: panos512/CMSKubernetes
          path: cmskubernetes

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      # - name: Login to DockerHub
      #   uses: docker/login-action@v1 
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build
      #   id: docker_build
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ${{ github.workspace }}/cmskubernetes/docker/das/
      #     file: ${{ github.workspace }}/cmskubernetes/docker/das/Dockerfile
      #     push: true
      #     tags: panos512/das:latest

      - name: Deploy new image in cluster
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
        with:
          args: '"get nodes"'